version: '3'
services:
  redis:
    image: redis:5.0-rc4-alpine
    ports:
      - "6389:6379"
    volumes:
      - ${PWD}/data/db/redis:/data
    user: "${UID}:${GID}"
    tty: true
    command: ["redis-server", "--appendonly", "yes"]
