version: '3'
services:
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/data/redis:/data
    user: "${UID}:${GID}"
    tty: true
    command: ["redis-server", "--appendonly", "yes"]
